# Control file for continuous integration testing at http://travis-ci.org/

language: c
compiler:
  - clang
  - gcc

os:
  - linux
  - osx

# For linux systems
addons:
  apt:
    packages:
    - liblzma-dev
    - libbz2-dev

# For MacOSX systems
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz; fi

before_script:
  - autoreconf -fi -I m4

script:
  - ./configure && make -e && make test
