# Alpine containerised builds
name: Alpine
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  alpine-job:
    runs-on: ubuntu-latest
    container: alpine:3.23
    strategy:
      fail-fast: false

    steps:
    - name: Install dependencies
      run: |
        apk update
        apk add git autoconf automake make gcc musl-dev perl bash zlib-dev bzip2-dev xz-dev curl-dev openssl-dev

    - name: Checkout
      # This is actions/checkout@v6.0.2
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: true
        persist-credentials: false

    - name: Configure
      run: |
        autoreconf -i
        ./configure --enable-werror --enable-plugins CFLAGS='-g -O3 -std=c99 -pedantic -Wno-sign-conversion'

    - name: Compile
      run: |
          make -j5

    - name: Check
      run: |
          make check
