name: Containers
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Containers:
    # comment out if we're using the cache
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        os:      ['alpine', 'archlinux', 'centos', 'rockylinux', 'opensuse']
        include:
          - os:      alpine
            image:   alpine:3.23
            cflags:  -Wno-sign-conversion
          - os:      archlinux
            image:   archlinux:base-devel
            cflags:  -Wno-sign-conversion -Wno-discarded-qualifiers
          - os:      centos
            image:   quay.io/centos/centos:10
          - os:      rockylinux
            image:   quay.io/rockylinux/rockylinux:10
            cflags:  -Wno-sign-conversion
          - os:      opensuse
            image:   opensuse/tumbleweed
            cflags:  -Wno-discarded-qualifiers

    steps:
      - name: Install dependencies
        run: |
          case ${{ matrix.os }} in
          *alpine*)
            apk update
            apk add git autoconf automake make gcc musl-dev perl bash zlib-dev bzip2-dev xz-dev curl-dev openssl-dev
            ;;
          *archlinux*)
            pacman -Syyu --noconfirm
            pacman -Sy --noconfirm base-devel git libdeflate
            ;;
          *centos*)
            yum install -y autoconf automake make gcc perl-Data-Dumper zlib-devel bzip2 bzip2-devel xz-devel curl-devel openssl-devel git perl-FindBin
            ;;
          *rockylinux*)
            yum install -y autoconf automake make gcc perl-Data-Dumper zlib-devel bzip2 bzip2-devel xz-devel curl-devel openssl-devel git perl-FindBin diffutils
            ;;
          *opensuse*)
            zypper --non-interactive install --allow-downgrade --force-resolution git autoconf automake make gcc perl zlib-devel libbz2-devel xz-devel libcurl-devel libopenssl-devel diffutils llvm-clang bzip2
            ;;
          esac

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true
          persist-credentials: false

      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-werror --enable-plugins CFLAGS="-g -O3 -std=c99 -pedantic ${{ matrix.cflags }}"

      - name: Build
        run: |
          make -j5

      - name: Test
        run: |
          make check
