name: OpenBSD

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: ['x86_64']
        #arch: ['x86_64', 'aarch64']  # currently disabled for speed
        # The OS supports riscv64 and powerpc64, but there are no prebuilt
        # binaries so we'd have to build dependencies from source
        #arch: ['x86_64', 'aarch64', 'riscv64', 'powerpc64']

    name: OpenBSD (${{ matrix.arch }})
    steps:

    - name: Checkout
      # This is actions/checkout@v6.0.2
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: true
        fetch-depth: 1

    - name: Setup VM
      uses: vmactions/openbsd-vm@v1
      with:
        # Note to use this you may need to merge all the steps into one.
        #debug-on-error: true
        #vnc-password: ${{ secrets.VNC_PASSWORD }}
        arch: ${{ matrix.arch }}
        usesh: true
        cpu: 4
        prepare: |
          pkg_add autoconf-2.71p0 automake-1.18.1 bash bzip2 curl gmake libdeflate xz

        run: |
          export AUTOCONF_VERSION=2.71
          export AUTOMAKE_VERSION=1.18
          autoreconf -i
          ./configure --with-libdeflate --enable-werror --enable-plugins CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib -Wl,-R/usr/local/lib"

    - name: Build
      shell: openbsd {0}
      run: |
        gmake -j5

    - name: Test
      shell: openbsd {0}
      run: |
        gmake check
