name: Solaris

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  solaris-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    name: Solaris (x86-64)
    steps:

    - name: Checkout
      # This is actions/checkout@v6.0.2
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        submodules: true
        fetch-depth: 1

    - name: Setup VM
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-clang-19"
        # Note to use this you may need to merge all the steps into one.
        #debug-on-error: true
        #vnc-password: ${{ secrets.VNC_PASSWORD }}
        usesh: true
        cpu: 4
        prepare: |
          pkg install autoconf automake bash curl bzip2

    - name: Configure
      shell: solaris {0}
      run: |
          autoreconf -i
          # The C library does casting in CMSG_SPACE, breaking ref_cache.
          # It also doesn't like -fstack-protector, but we only check compile
          # rather than link time, so disable that too.  We add to CPPFLAGS
          # as it occurs after REF_CACHE_EXTRA_C_FLAGS.
          ./configure --enable-werror CPPFLAGS="-Wno-sign-conversion -fno-stack-protector"

    - name: Build
      shell: solaris {0}
      run: |
          gmake -j5

    - name: Test
      shell: solaris {0}
      run: |
          # We need more compliant versions of tr and grep.
          PATH=/usr/xpg4/bin:$PATH
          export PATH
          gmake check
