name: VMs
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # ----------
  FreeBSD:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      #matrix:
      #  arch:    ['x86_64', 'aarch64']

    steps:
      - name: Checkout
        # This is actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup VM
        # This is vmactions/freebsd-vm@@v1.5.2
        uses: vmactions/freebsd-vm@77ed28d336d03fe19a3f4f7266c1d2c4714dd79d
        with:
          #debug-on-error: true
          #vnc-password: ${{ secrets.VNC_PASSWORD }}
          #arch: ${{ matrix.arch }}
          usesh: true
          cpu: 4
          prepare: |
            pkg update
            pkg install -y autoconf automake bash curl bzip2 gmake libdeflate perl5

      # Inside VM
      - name: Configure
        shell: freebsd {0}
        run: |
          autoreconf -i
          ./configure --with-libdeflate --enable-werror --enable-plugins CFLAGS="-g -O3 -fsanitize=address,undefined -DHTS_ALLOW_UNALIGNED=0 -Wno-format-truncation -Wno-format-overflow" CPPFLAGS="-I/usr/local/include" LDFLAGS="-fsanitize=address,undefined -L/usr/local/lib -Wl,-R/usr/local/lib"

      - name: Build
        shell: freebsd {0}
        run: |
          gmake -j5

      - name: Test
        shell: freebsd {0}
        run: |
          gmake check

  # ----------
  OpenBSD:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        # This is actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup VM
        # This is vmactions/openbsd-vm@v1.4.5
        uses: vmactions/openbsd-vm@c941015845c0f0c429676840963dc63b226d4f69
        with:
          usesh: true
          cpu: 4
          prepare: |
            pkg_add autoconf-2.71p0 automake-1.18.1 bash bzip2 curl gmake libdeflate xz

      # Inside VM
      - name: Configure
        shell: openbsd {0}
        run: |
          export AUTOCONF_VERSION=2.71
          export AUTOMAKE_VERSION=1.18
          autoreconf -i
          ./configure --with-libdeflate --enable-werror CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib -Wl,-R/usr/local/lib"

      - name: Build
        shell: openbsd {0}
        run: |
          gmake -j5

      - name: Test
        shell: openbsd {0}
        run: |
          gmake check

  # ----------
  Solaris:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        # This is actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true
          fetch-depth: 1

      - name: Setup VM
        # This is vmactions/solaris-vm@v1.3.8
        uses: vmactions/solaris-vm@315163f088b66e55bbcc45928bd224d4973b2312
        with:
          release: "11.4-clang-19"
          usesh: true
          cpu: 4
          prepare: |
            pkg install autoconf automake bash curl bzip2

      # Inside VM
      - name: Configure
        shell: solaris {0}
        run: |
          autoreconf -i
          # The C library does casting in CMSG_SPACE, breaking ref_cache.
          # It also doesn't like -fstack-protector, but we only check compile
          # rather than link time, so disable that too.  We add to CPPFLAGS
          # as it occurs after REF_CACHE_EXTRA_C_FLAGS.
          ./configure --enable-werror CPPFLAGS="-Wno-sign-conversion -fno-stack-protector"

      - name: Build
        shell: solaris {0}
        run: |
          gmake -j5

      - name: Test
        shell: solaris {0}
        run: |
          # We need more compliant versions of tr and grep.
          PATH=/usr/xpg4/bin:$PATH
          export PATH
          gmake check
